name: market_data_exploration
channels:
  - conda-forge
dependencies:
  - python=3.13
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - scipy
  - pip:
    - yfinance
    - python-dotenv
    - mkdocs
    - -e .