name: market_data_exploration
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ta-lib
  - ipython
  - pip:


    - jupyterlab
    - matplotlib
    - notebook
    - statsmodels
    - pandas
    - scikit-learn
    - xgboost
    - plotly
    - scipy
    - yfinance
    - tensorflow
    - qstrader 
    - backtrader
    - QuantLib
    - python-dotenv
    - mkdocs
    - -e .