name: market_data_exploration
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - statsmodels
  - pandas
  - scikit-learn
  - xgboost
  - plotly
  - scipy
  - ta-lib
  - pip:
    - yfinance
    - qstrader 
    - backtrader
    - QuantLib
    - python-dotenv
    - mkdocs
    - -e .